NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-7700-ca-benzmanufacturer.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-7700-ca-benzmanufacturer.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-7700-ca-benzmanufacturer.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-7700-ca-benzmanufacturer.pem
    OrganizationalUnitIdentifier: orderer
